=== Royz29/IntegrativeProgramming/public/receipt.dtd
<!ELEMENT cart (item+, total_price)>
<!ELEMENT item (product_id, name, quantity, image, price, total_price, price_per_unit)>
<!ELEMENT product_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT total_price (#PCDATA)>
<!ELEMENT price_per_unit (#PCDATA)>
<!ELEMENT net_unit (#PCDATA)>

=== Royz29/IntegrativeProgramming/public/receipt.xml
<?xml version="1.0"?>
<!DOCTYPE cart SYSTEM "receipt.dtd">
<cart>
  <item>
    <userId>2</userId>
    <product_id>1</product_id>
    <name>Laptop 1</name>
    <quantity>1</quantity>
    <image>1683632848.jpeg</image>
    <price>25.00</price>
    <created_at>2023-05-11 19:38:56</created_at>
    <total_price>25</total_price>
    <price_per_unit>25.00</price_per_unit>
  </item>
<item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>1</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:39:24</created_at><total_price>25</total_price><price_per_unit>25.00</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-11 19:43:10</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>1</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:46:30</created_at><total_price>25</total_price><price_per_unit>25.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>1</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:47:49</created_at><total_price>25</total_price><price_per_unit>25.00</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-11 19:47:50</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-11 19:48:08</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-11 19:48:08</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-11 19:48:08</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>2</userId><product_id>3</product_id><name>Smart TV 1</name><quantity>1</quantity><image>1683632904.jpeg</image><price>51.00</price><created_at>2023-05-11 19:49:27</created_at><total_price>51</total_price><price_per_unit>51.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>1</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:49:28</created_at><total_price>25</total_price><price_per_unit>25.00</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-11 19:49:37</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>2</userId><product_id>3</product_id><name>Smart TV 1</name><quantity>1</quantity><image>1683632904.jpeg</image><price>51.00</price><created_at>2023-05-11 19:49:39</created_at><total_price>51</total_price><price_per_unit>51.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>1</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:49:40</created_at><total_price>25</total_price><price_per_unit>25.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>1</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:51:41</created_at><total_price>25</total_price><price_per_unit>25.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>Laptop 1</name><quantity>2</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-11 19:53:49</created_at><total_price>50</total_price><price_per_unit>25</price_per_unit></item><item><userId>1</userId><product_id>2</product_id><name>Laptop 2</name><quantity>1</quantity><image>1683632868.jpeg</image><price>22.00</price><created_at>2023-05-12 06:55:12</created_at><total_price>22</total_price><price_per_unit>22.00</price_per_unit></item><item><userId>1</userId><product_id>5</product_id><name>Phone 1</name><quantity>7</quantity><image>1683632946.jpeg</image><price>12.00</price><created_at>2023-05-12 13:45:32</created_at><total_price>84</total_price><price_per_unit>12</price_per_unit></item><item><userId>1</userId><product_id>6</product_id><name>Phone 2</name><quantity>86</quantity><image>1683632962.jpg</image><price>22.00</price><created_at>2023-05-12 13:47:32</created_at><total_price>1892</total_price><price_per_unit>22</price_per_unit></item><item><userId>1</userId><product_id>1</product_id><name>Laptop 1</name><quantity>3</quantity><image>1683632848.jpeg</image><price>25.00</price><created_at>2023-05-12 13:49:32</created_at><total_price>75</total_price><price_per_unit>25</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>iPhone 14 Pro Max</name><quantity>3</quantity><image>1684240168.jpeg</image><price>9500.00</price><created_at>2023-05-16 12:48:28</created_at><total_price>28500</total_price><price_per_unit>9500</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>Samsung Galaxy S23+</name><quantity>3</quantity><image>1684240320.jpeg</image><price>3000.00</price><created_at>2023-05-16 12:48:52</created_at><total_price>9000</total_price><price_per_unit>3000</price_per_unit></item><item><userId>1</userId><product_id>1</product_id><name>asd</name><quantity>1</quantity><image>1684248728.jpeg</image><price>2.00</price><created_at>2023-05-16 14:54:57</created_at><total_price>2</total_price><price_per_unit>2.00</price_per_unit></item><item><userId>2</userId><product_id>1</product_id><name>P{o</name><quantity>3</quantity><image>1684248877.jpeg</image><price>11.00</price><created_at>2023-05-17 06:20:02</created_at><total_price>33</total_price><price_per_unit>11</price_per_unit></item><item><userId>2</userId><product_id>2</product_id><name>asdasd</name><quantity>2</quantity><image>1684248907.jpeg</image><price>123.00</price><created_at>2023-05-17 06:20:03</created_at><total_price>246</total_price><price_per_unit>123</price_per_unit></item></cart>
